//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ethko
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadStatus
    {
        public int LeadStatusId { get; set; }
        public string LeadStatusName { get; set; }
        public string FstUser { get; set; }
        public System.DateTime InsDate { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
