//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ethko
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead
    {
        public int LeadId { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string MName { get; set; }
        public string FullName { get; set; }
        public Nullable<int> PotentialValue { get; set; }
        public int ReferralSourceId { get; set; }
        public int LeadStatusId { get; set; }
        public int PracticeAreaId { get; set; }
        public string AssignTo { get; set; }
        public Nullable<int> ReferredByContact { get; set; }
        public Nullable<int> ReferredByCompany { get; set; }
        public int DateAdded { get; set; }
        public string Title { get; set; }
        public short Archived { get; set; }
        public string Email { get; set; }
        public string CellPhone { get; set; }
        public string WorkPhone { get; set; }
        public string HomePhone { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string License { get; set; }
        public string Website { get; set; }
        public string LeadNotes { get; set; }
        public string CaseNotes { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string FstUser { get; set; }
        public int InsDate { get; set; }
        public int LstDate { get; set; }
        public string LstUser { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Company Company { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual LeadReferralSource LeadReferralSource { get; set; }
        public virtual LeadStatus LeadStatus { get; set; }
        public virtual PracticeArea PracticeArea { get; set; }
    }
}
