//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ethko
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationId { get; set; }
        public string UserId { get; set; }
        public int N1 { get; set; }
        public string LstUser { get; set; }
        public System.DateTime LstDate { get; set; }
        public string FstUser { get; set; }
        public System.DateTime InsDate { get; set; }
        public byte[] RowVersion { get; set; }
        public int N2 { get; set; }
        public int N3 { get; set; }
        public int N4 { get; set; }
        public int N5 { get; set; }
        public int N6 { get; set; }
        public int N7 { get; set; }
        public int N8 { get; set; }
        public int N9 { get; set; }
        public int N10 { get; set; }
        public int N11 { get; set; }
        public int N12 { get; set; }
        public int N13 { get; set; }
        public int N14 { get; set; }
        public int N15 { get; set; }
        public int N16 { get; set; }
        public int N17 { get; set; }
        public int N18 { get; set; }
        public int N19 { get; set; }
        public int N20 { get; set; }
        public int N21 { get; set; }
        public int N22 { get; set; }
        public int N23 { get; set; }
        public int N24 { get; set; }
        public int N25 { get; set; }
        public int N26 { get; set; }
        public int N27 { get; set; }
        public int N28 { get; set; }
        public int N29 { get; set; }
        public int N30 { get; set; }
        public int N31 { get; set; }
        public int N32 { get; set; }
        public int N33 { get; set; }
        public int N34 { get; set; }
        public int N35 { get; set; }
        public int N36 { get; set; }
        public int N37 { get; set; }
        public int N38 { get; set; }
        public int N39 { get; set; }
        public int N40 { get; set; }
        public int N41 { get; set; }
        public int N42 { get; set; }
        public int N43 { get; set; }
        public int N44 { get; set; }
        public int N45 { get; set; }
        public int N46 { get; set; }
        public int N47 { get; set; }
        public int N48 { get; set; }
        public int N49 { get; set; }
        public int N50 { get; set; }
        public int N51 { get; set; }
        public int N52 { get; set; }
        public int N53 { get; set; }
        public int N54 { get; set; }
        public int N55 { get; set; }
        public int N56 { get; set; }
        public int N57 { get; set; }
        public int N58 { get; set; }
        public int N59 { get; set; }
        public int N60 { get; set; }
        public int N61 { get; set; }
        public int N62 { get; set; }
        public int N63 { get; set; }
        public int N64 { get; set; }
        public int N65 { get; set; }
        public int N66 { get; set; }
        public int N67 { get; set; }
        public int N68 { get; set; }
        public int N69 { get; set; }
        public int N70 { get; set; }
        public int N71 { get; set; }
        public int N72 { get; set; }
        public int N73 { get; set; }
        public int N74 { get; set; }
        public int N75 { get; set; }
        public int N76 { get; set; }
        public int N77 { get; set; }
        public int N78 { get; set; }
        public int N79 { get; set; }
        public int N80 { get; set; }
        public int N81 { get; set; }
        public int N82 { get; set; }
        public int N83 { get; set; }
        public int N84 { get; set; }
        public int N85 { get; set; }
        public int N86 { get; set; }
        public int N87 { get; set; }
        public int N88 { get; set; }
        public int N89 { get; set; }
        public int N90 { get; set; }
        public int N91 { get; set; }
        public int N92 { get; set; }
        public int N93 { get; set; }
        public int N94 { get; set; }
        public int N95 { get; set; }
        public int N96 { get; set; }
        public int N97 { get; set; }
        public int N98 { get; set; }
        public int N99 { get; set; }
        public int N100 { get; set; }
        public int N101 { get; set; }
        public int N102 { get; set; }
        public int N103 { get; set; }
        public int N104 { get; set; }
        public int N105 { get; set; }
        public int N106 { get; set; }
        public int N107 { get; set; }
        public int N108 { get; set; }
        public int N109 { get; set; }
        public int N110 { get; set; }
        public int N111 { get; set; }
    }
}
