//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ethko
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationId { get; set; }
        public string UserId { get; set; }
        public string N1 { get; set; }
        public string N2 { get; set; }
        public string N3 { get; set; }
        public string N4 { get; set; }
        public string N5 { get; set; }
        public string N6 { get; set; }
        public string N7 { get; set; }
        public string N8 { get; set; }
        public string N9 { get; set; }
        public string N10 { get; set; }
        public string N11 { get; set; }
        public string N12 { get; set; }
        public string N13 { get; set; }
        public string N14 { get; set; }
        public string N15 { get; set; }
        public string N16 { get; set; }
        public string N17 { get; set; }
        public string N18 { get; set; }
        public string N19 { get; set; }
        public string N20 { get; set; }
        public string N21 { get; set; }
        public string N22 { get; set; }
        public string N23 { get; set; }
        public string N24 { get; set; }
        public string N25 { get; set; }
        public string N26 { get; set; }
        public string N27 { get; set; }
        public string N28 { get; set; }
        public string N29 { get; set; }
        public string N30 { get; set; }
        public string N31 { get; set; }
        public string N32 { get; set; }
        public string N33 { get; set; }
        public string N34 { get; set; }
        public string N35 { get; set; }
        public string N36 { get; set; }
        public string N37 { get; set; }
        public string N38 { get; set; }
        public string N39 { get; set; }
        public string N40 { get; set; }
        public string N41 { get; set; }
        public string N42 { get; set; }
        public string N43 { get; set; }
        public string N44 { get; set; }
        public string N45 { get; set; }
        public string N46 { get; set; }
        public string N47 { get; set; }
        public string N48 { get; set; }
        public string N49 { get; set; }
        public string N50 { get; set; }
        public string N51 { get; set; }
        public string N52 { get; set; }
        public string N53 { get; set; }
        public string N54 { get; set; }
        public string N55 { get; set; }
        public string N56 { get; set; }
        public string N57 { get; set; }
        public string N58 { get; set; }
        public string N59 { get; set; }
        public string N60 { get; set; }
        public string N61 { get; set; }
        public string N62 { get; set; }
        public string N63 { get; set; }
        public string N64 { get; set; }
        public string N65 { get; set; }
        public string N66 { get; set; }
        public string N67 { get; set; }
        public string N68 { get; set; }
        public string N69 { get; set; }
        public string N70 { get; set; }
        public string N71 { get; set; }
        public string N72 { get; set; }
        public string N73 { get; set; }
        public string N74 { get; set; }
        public string N75 { get; set; }
        public string N76 { get; set; }
        public string N77 { get; set; }
        public string N78 { get; set; }
        public string N79 { get; set; }
        public string N80 { get; set; }
        public string N81 { get; set; }
        public string N82 { get; set; }
        public string N83 { get; set; }
        public string N84 { get; set; }
        public string N85 { get; set; }
        public string N86 { get; set; }
        public string N87 { get; set; }
        public string N88 { get; set; }
        public string N89 { get; set; }
        public string N90 { get; set; }
        public string N91 { get; set; }
        public string N92 { get; set; }
        public string N93 { get; set; }
        public string N94 { get; set; }
        public string N95 { get; set; }
        public string N96 { get; set; }
        public string N97 { get; set; }
        public string N98 { get; set; }
        public string N99 { get; set; }
        public string N100 { get; set; }
        public string N101 { get; set; }
        public string N102 { get; set; }
        public string N103 { get; set; }
        public string N104 { get; set; }
        public string N105 { get; set; }
        public string N106 { get; set; }
        public string N107 { get; set; }
        public string N108 { get; set; }
        public string N109 { get; set; }
        public string N110 { get; set; }
        public string N111 { get; set; }
        public string N112 { get; set; }
        public string N113 { get; set; }
        public string N114 { get; set; }
        public string N115 { get; set; }
        public string N116 { get; set; }
        public string N117 { get; set; }
        public string N118 { get; set; }
        public string N119 { get; set; }
        public string N120 { get; set; }
        public string N121 { get; set; }
        public string N122 { get; set; }
        public string N123 { get; set; }
        public string N124 { get; set; }
        public string N125 { get; set; }
        public string N126 { get; set; }
        public string N127 { get; set; }
        public string N128 { get; set; }
        public string N129 { get; set; }
        public string N130 { get; set; }
        public string N131 { get; set; }
        public string N132 { get; set; }
        public string N133 { get; set; }
        public string N134 { get; set; }
        public string N135 { get; set; }
        public string N136 { get; set; }
        public string N137 { get; set; }
        public string N138 { get; set; }
        public string N139 { get; set; }
        public string N140 { get; set; }
        public string N141 { get; set; }
        public string N142 { get; set; }
        public string N143 { get; set; }
        public string N144 { get; set; }
        public string N145 { get; set; }
        public string N146 { get; set; }
        public string N147 { get; set; }
        public string N148 { get; set; }
        public string N149 { get; set; }
        public string N150 { get; set; }
        public string LstUser { get; set; }
        public System.DateTime LstDate { get; set; }
        public string FstUser { get; set; }
        public System.DateTime InsDate { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
